### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by adilatilgan** [kocun/heida#179]
Some reports about 
Ubuntu 12.04 + nodejs 6.11 

info: Starting app...

info: Could not find module: ejs in path: /home/heida/heida/node_modules
/usr/lib/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:281
throw e;
^

`include-all` attempted to `require(/home/heida/heida/api/services/passport.js)`, but an error occurred::
Details:Error: Cannot find module 'bcrypt'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/home/heida/heida/api/services/passport.js:6:12)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at /usr/lib/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:271:33
at Array.forEach (native)
at _recursivelyIncludeAll (/usr/lib/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:174:11)
at includeAll (/usr/lib/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:292:5)
at helpBuildDictionary (/usr/lib/node_modules/sails/node_modules/include-all/lib/help-build-dictionary.js:43:15)
at Function.module.exports.optional (/usr/lib/node_modules/sails/node_modules/include-all/index.js:67:10)
at Hook.loadServices (/usr/lib/node_modules/sails/lib/hooks/moduleloader/index.js:424:18)
at Hook.wrapper [as loadServices] (/usr/lib/node_modules/sails/node_modules/@sailshq/lodash/lib/index.js:3250:19)
at Hook.loadModules (/usr/lib/node_modules/sails/lib/hooks/services/index.js:68:21)
at Hook.wrapper [as loadModules] (/usr/lib/node_modules/sails/node_modules/@sailshq/lodash/lib/index.js:3250:19)

**Comment by digifelis** [comment]
"sails lift" komutundan önce
"npm install" komutu kullanılmalıdır. böylelikle sails için package.json içerisinde belirtilen bağımlılıklar yüklenecektir.
